//
//  HomeModels.swift
//  DesafioMarvel
//
//  Created by Gustavo Melki Leal on 17/05/2018.
//  Copyright (c) 2018 gustavoMelki. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
  // MARK: Use cases
  
  enum Something {
    struct Request {
      var name: String
    }
    struct Response {
      
    }
    struct ViewModel {
      
    }
  }
}
